- id: ensure-finnish-translation
  version: 1.0.0
  name: Ensure Finnish translation
  description: Ensure Finnish translation of Odoo module exists
  entry: ensure-finnish-translation
  language: python
  types: [python]
  stages: [pre-commit, pre-merge-commit, manual]
  pass_filenames: false