name: Odoo Pre-Commit

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use for pre-commit'
        required: false
        default: '3.11'
        type: string

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # required by pre-commit for Git operations

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      # Install dependencies for pre-commit if needed
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      # Run pre-commit checks
      - name: Run pre-commit
        run: pre-commit run --all-files

