exclude: |
  (?x)
  ^views_migration_17/|
  ^setup/|/static/description/index\.html$|
  .svg$|/tests/([^/]+/)?cassettes/|^.copier-answers.yml$|^.github/|
  ^README\.md$|
  /static/(src/)?lib/|
  ^docs/_templates/.*\.html$|
  readme/.*\.(rst|md)$|
  /build/|/dist/|
  (LICENSE.*|COPYING.*)

default_language_version:
  python: python3
  node: "16.17.0"

repos:
  # Generic shared hooks
  - repo: https://github.com/sbidoul/whool
    rev: v0.5
    hooks:
      - id: whool-init

  - repo: https://github.com/OCA/odoo-pre-commit-hooks
    rev: v0.0.25
    hooks:
      - id: oca-checks-odoo-module
      - id: oca-checks-po

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: /README\.rst$|\.pot?$
      - id: end-of-file-fixer
        exclude: /README\.rst$|\.pot?$
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]

  # Maintainer tools with defaults
  - repo: https://github.com/oca/maintainer-tools
    rev: f71041f22b8cd68cf7c77b73a14ca8d8cd190a60
    hooks:
      - id: oca-update-pre-commit-excluded-addons
      - id: oca-fix-manifest-website
        args: ["https://github.com/tawasta/CHANGE_ME"]
      - id: oca-gen-addon-readme
        args:
          - --addons-dir=.
          - --branch=17.0
          - --org-name=Futural
          - --repo-name=CHANGE_ME
          - --if-source-changed
          - --keep-source-digest
          - --convert-fragments-to-markdown
      - id: oca-gen-external-dependencies
      - id: oca-gen-addons-table


